

name: Build and Deploy Flask App to GCE

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install google cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "myprojectprakash1"
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          export_default_credentials: true
  

      - name: Build and push the docker image
        env:
          GOOGLE_PROJECT: myprojectprakash1
        run: |
          gcloud auth configure-docker us-central-1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myflaskimg:latest .
          docker push us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myflaskimg:latest


    
