name: Build and Deploy Flask App to GCE

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/273844163073/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-pool"
          service_account: "273844163073-compute@developer.gserviceaccount.com"
          project_id: "myprojectprakash1"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1  

      - name: Configure Docker
        run: gcloud auth configure-docker

      # Get the GCloud credentials from the previous step
      - id: gcloud-credentials
        run: echo ${{ steps.auth.outputs.credentials }} > gcloud-service-key.json


      - name: Authenticate to Artifact Registry with Docker
        env:
          GCLOUD_SERVICE_KEY: ${{ steps.gcloud-credentials.outputs.result }}
        run: |
         echo "$GCLOUD_SERVICE_KEY" | base64 -d | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          

      - name: Build Docker Image
        run: docker build -t myprojectprakash1 .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker tag myprojectprakash1 us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myprojectprakash1:latest
          docker push us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myprojectprakash1:latest

      - name: Update Compute Engine Instance
        run: |
          gcloud compute instances update-container instance-20240723-125548 \
            --zone us-central1-b \
            --container-image us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myprojectprakash1:latest
