name: Build and Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: docker build -t myprojectprakash1

      - name: Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker tag your-project-name us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myprojectprakash1:latest
          docker push us-central1-docker.pkg.dev/myprojectprakash1/myflaskappmyprojectprakash1:latest

      - name: Update Compute Engine Instance
        run: |
          gcloud compute instances update-container instance-20240723-125548 \
            --zone us-central1-b \
            --container-image us-central1-docker.pkg.dev/myprojectprakash1/myflaskapp/myprojectprakash1:latest
