name: Deploy to GCE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | script -c "docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"

      - name: Build and push Docker image
        run: |
          docker build -t prakashdanabal93/myflaskappimg
          docker push prakashdanabal93/myflaskappimg

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GCE
        uses: appleboy/ssh-action@master
        with:
          host: 34.42.139.117
          username: prakashdanabal93@gmail.com
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull prakashdanabal93/myflaskappimg
            sudo docker stop flask-website || true 
            sudo docker rm flask-website || true
            sudo docker run -d -p 80:8080 --name flask-website prakashdanabal93/myflaskappimg
